### ISSUE TITLE
I cannot run it on lambda

### ISSUE THREAD

**Issue by anarua1203** [ventz/whisper-openai-container#2]
Hi, could you please give a hand.

I was just testing locally and it runs perfect, but when trying to execute on lambda I get this error 

[Errno 8] Exec format error: 'ffmpeg'

Don't know if perhaps you have a workaround

**Comment by ventz** [comment]
@anarua1203 Try the updated version I just pushed out, specifically, the updated Dockerfile.

I believe the issue you saw is due to the developer that maintains the static version of ffmpeg bumping the version number. He recommends following the latest release, and it changed the extracted folder name. I added a wild card to deal with this in the future.

I also updated Lambda to v3.12, moved away from yum to dnf (as v3.12 forced the change), added a note about the required amd64 architecture due to the related statically compiled ffmpeg and a note about building on a Mac M-series.

Let me know if this works for you.

**Comment by ventz** [comment]
@anarua1203 Actually, the fact that you said it runs locally makes me think you are running into the architecture issue between your local machine and your AWS Lambda.

1.) Make sure that you are deploying a x86-64 compatible ('amd64') Lambdas. This is needed due to ffmpeg being statically compiled for amd64.

2.) If you are building on a Mac M-series, you are building a ARM64 and trying to push that - see the note I added to the bottom of the README about that.

**Comment by anarua1203** [comment]
Thank you so much!!

You were right about platform, Is working now

**Comment by ventz** [comment]
Great!

Np at all.
